### ISSUE TITLE
Can you add more parameters?

### ISSUE THREAD

**Issue by roncakjakub** [jachzen/cunning_document_scanner#39]
Hi, i want to ask, if it possible, to let me set some parameters like:

- disable auto capturing when i wait on one place. It scans everything around :( ... 
- disable scanner ... this package is the best in matter of camera plugin with enabled multi capture, that is beautifully designed, fast, with translate and well working. Now there is some parameter crop, but it does nothing :( 
- disable selfie mode

Thanks..  hope it wont be such problem :) 

And thanks for such great plugin

**Comment by vicajilau** [comment]
We are pleased that you like cunning_document_scanner. The reason they don't look the same on Android and iOS is because iOS uses a native implementation called [VNDocumentCameraViewController](https://developer.apple.com/documentation/visionkit/vndocumentcameraviewcontroller). Regarding the parameter passing is precisely what we are working on and we are even considering the idea of completely rewriting the iOS scanner so that it is the same on both platforms.

**Comment by vicajilau** [comment]
A number of changes have been made to the master branch of the project. It is worth noting that one of the changes is that now that more parameters are accepted and parameters with names are used
